name: codequality

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.3.9]

    name: PHP-${{ matrix.php }} 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: main

    - name: Checkout WP2Static
      uses: actions/checkout@v2
      with:
        repository: WP2Static/wp2static
        path: wp2static

    - name: Cache PHP dependencies
      uses: actions/cache@v1
      with:
        path: main/vendor
        key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
        coverage: none

    - name: Validate Composer
      run: composer validate --strict
      working-directory: main

    - name: Install PHP dependencies
      run: composer install --no-interaction --no-suggest
      working-directory: main

    - name: Run our Linter and PHPStan
      run: composer test
      working-directory: main
